[package]
name = "shvclient"
description = "A Rust framework for Silicon Heaven RPC devices"
license = "MIT"
repository = "https://github.com/silicon-heaven/libshvclient-rs"
version = "0.26.1"
edition = "2024"

[lib]
name = "shvclient"
path = "src/lib.rs"

[[example]]
name = "simple_device_tokio"
path = "examples/simple_device_tokio.rs"
required-features = ["tokio"]

[[example]]
name = "simple_device_smol"
path = "examples/simple_device_smol.rs"
required-features = ["smol"]

[[test]]
name = "ssl"
path = "tests/ssl.rs"

[dev-dependencies]
clap = { version = "4.4", features = ["derive"] }
simple_logger = { version = "5.0.0", features = ["stderr"] }
generics-alias = { git = "https://github.com/j4r0u53k/generics-alias-rs.git", branch = "main" }
shvbroker = "3.20.13"
rcgen = "0.14.5"
tempfile = "3.23.0"
smol = "2.0.2"
anyhow = "1.0.100"

[dependencies]
shvproto = "6.0.1"
shvrpc = "10.0"
futures = "0.3.29"
futures-time = "3.0.0"
url = "2.4.1"
log = "0.4.20"
duration-str = "0.19"
async-broadcast = "0.7.1"
tokio = { version = "1.49.0", features = ["macros", "net", "rt-multi-thread", "time"], optional = true }
tokio-util = { version = "0.7.10", features = ["compat"], optional = true }
smol = { version = "2.0.2", optional = true }

# NOTE: macro_magic needs to be here as a direct dependency because some functions from
# there are called in expansion of `generics_inner` macro from generics-alias crate.
macro_magic = "0.6.0"

futures-rustls = "0.26.1"
rustls-pemfile = "2.2.0"
rustls-platform-verifier = "0.6.1"
async-trait = "0.1.89"

# For local development
# [patch.crates-io]
# shvproto = { path = "../libshvproto-rs" }
# shvrpc = { path = "../libshvrpc-rs" }

[features]
default = []
tokio = ["dep:tokio", "dep:tokio-util"]
smol = ["dep:smol"]
mocking = []
